#!/usr/bin/env bash
# Freeze the Miasm (cea-sec/miasm) documentation into the :Docs frozen web-book
# layout used by the miasm "Browse Documentation" picker:
#   Resources/docs/miasm-docs/index.tsv          "<title>\t<url>" in tree order
#   Resources/docs/.webcache/<sha256(url)>.txt     the rendered module/guide
#
# Miasm publishes no docs site, so the API reference is GENERATED by static `ast`
# docstring extraction from the source (no build, no import of the 11 C
# extensions): one page per .py module across the 8 sub-packages. The doc/ guides
# are 4 Jupyter notebooks converted to markdown, plus 2 cheatsheet PDFs. Each
# entry is keyed by a stable github blob URL (also openable in a browser).
# Usage: miasm_docs_build.sh   (needs git, python3, pdftotext)
set -u
CFG="${CFG:-$(cd "$(dirname "$0")/../.." && pwd)}"
CACHE="$CFG/Resources/docs/.webcache"
OUT="$CFG/Resources/docs/miasm-docs"
SRC=$(mktemp -d)
mkdir -p "$OUT" "$CACHE"

echo "==> cloning cea-sec/miasm (shallow)"
git clone --depth 1 -q https://github.com/cea-sec/miasm "$SRC" || { echo "clone failed" >&2; exit 1; }

CACHE="$CACHE" OUT="$OUT" SRC="$SRC" python3 - <<'PY'
import os, ast, json, hashlib, subprocess, glob
CACHE, OUT, SRC = os.environ["CACHE"], os.environ["OUT"], os.environ["SRC"]
BLOB = "https://github.com/cea-sec/miasm/blob/master"
rows = []

def cache(url, text):
    cf = os.path.join(CACHE, hashlib.sha256(url.encode()).hexdigest() + ".txt")
    open(cf, "w", encoding="utf-8").write(text.rstrip() + "\n")

def add(title, url, text):
    cache(url, text)
    rows.append("%s\t%s" % (title, url))

def label(title):
    rows.append(title)

def sig(fn):
    try:
        return "%s(%s)" % (fn.name, ast.unparse(fn.args))
    except Exception:
        return fn.name + "(...)"

def render_module(path, dotted):
    with open(path, encoding="utf-8", errors="replace") as f:
        srctext = f.read()
    try:
        tree = ast.parse(srctext)
    except SyntaxError:
        return "# %s\n\n(could not parse)\n" % dotted
    out = ["# %s\n" % dotted]
    doc = ast.get_docstring(tree)
    if doc:
        out.append(doc.strip() + "\n")
    # module-level UPPER_CASE constants (VERSION, etc.)
    consts = []
    for n in tree.body:
        if isinstance(n, ast.Assign):
            for t in n.targets:
                if isinstance(t, ast.Name) and (t.id.isupper() or t.id == "VERSION"):
                    try:
                        consts.append("`%s = %s`" % (t.id, ast.unparse(n.value)))
                    except Exception:
                        consts.append("`%s`" % t.id)
    if consts:
        out.append("## Module variables\n\n" + "\n".join("- " + c for c in consts) + "\n")
    classes = [n for n in tree.body if isinstance(n, ast.ClassDef)]
    funcs = [n for n in tree.body if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef))]
    if classes:
        out.append("## Classes\n")
        for c in classes:
            bases = ", ".join(ast.unparse(b) for b in c.bases) if c.bases else ""
            out.append("### class `%s%s`\n" % (c.name, "(" + bases + ")" if bases else ""))
            cdoc = ast.get_docstring(c)
            if cdoc:
                out.append(cdoc.strip() + "\n")
            methods = [m for m in c.body if isinstance(m, (ast.FunctionDef, ast.AsyncFunctionDef))]
            for m in methods:
                mdoc = ast.get_docstring(m)
                line = "- **`%s`**" % sig(m)
                if mdoc:
                    first = mdoc.strip().split("\n")[0]
                    line += " - " + first
                out.append(line)
            if methods:
                out.append("")
    if funcs:
        out.append("## Functions\n")
        for fn in funcs:
            out.append("### `%s`\n" % sig(fn))
            fdoc = ast.get_docstring(fn)
            if fdoc:
                out.append(fdoc.strip() + "\n")
    return "\n".join(out)

# ---- API reference: one page per .py under the 8 sub-packages + __init__ ----
label("API Reference")
PKGS = ["__init__.py", "analysis", "arch", "core", "expression", "ir", "jitter", "loader", "os_dep"]
paths = []
for p in PKGS:
    full = os.path.join(SRC, "miasm", p)
    if p.endswith(".py"):
        paths.append(os.path.join(SRC, "miasm", "__init__.py"))
    else:
        paths += glob.glob(os.path.join(full, "**", "*.py"), recursive=True)
paths = sorted(set(paths))
api = 0
for path in paths:
    rel = os.path.relpath(path, SRC)          # miasm/analysis/machine.py
    parts = rel[:-3].split("/")               # ["miasm","analysis","machine"]
    if parts[-1] == "__init__":
        parts = parts[:-1]                    # package landing page
    dotted = ".".join(parts)
    indent = "  " * len(parts)                # miasm=2sp, miasm.analysis=4sp, ...
    url = "%s/%s" % (BLOB, rel)
    body = render_module(path, dotted)
    if len(body) < 20:
        continue
    add(indent + dotted, url, body)
    api += 1

# ---- Guides: the doc/ notebooks converted to markdown ----
def ipynb_to_md(path):
    nb = json.load(open(path, encoding="utf-8"))
    out = []
    for cell in nb.get("cells", []):
        src = "".join(cell.get("source", []))
        if not src.strip():
            continue
        if cell.get("cell_type") == "markdown":
            out.append(src)
        elif cell.get("cell_type") == "code":
            out.append("```python\n" + src + "\n```")
    return "\n\n".join(out)

label("Guides")
GUIDES = [
    ("Guide: Expression", "doc/expression/expression.ipynb"),
    ("Guide: IR lifting", "doc/ir/lift.ipynb"),
    ("Guide: Jitter", "doc/jitter/jitter.ipynb"),
    ("Guide: LocationDB", "doc/locationdb/locationdb.ipynb"),
]
for title, rel in GUIDES:
    path = os.path.join(SRC, rel)
    if not os.path.exists(path):
        print("  missing", rel); continue
    body = "# %s\n\n%s" % (title[7:], ipynb_to_md(path))
    add("  " + title, "%s/%s" % (BLOB, rel), body)

# ---- Cheatsheets: the doc/ PDFs via pdftotext ----
label("Cheatsheets")
SHEETS = [
    ("Cheatsheet: Disassembler", "doc/cheatsheets/reminder_disassembler.pdf"),
    ("Cheatsheet: Sandbox", "doc/cheatsheets/reminder_sandbox.pdf"),
]
for title, rel in SHEETS:
    path = os.path.join(SRC, rel)
    if not os.path.exists(path):
        print("  missing", rel); continue
    txt = subprocess.run(["pdftotext", "-layout", "-nopgbrk", path, "-"],
                         capture_output=True, text=True).stdout
    body = "# %s\n\n(Visual reminder - exported from a diagram; text below.)\n\n%s" % (title[12:], txt)
    add("  " + title, "%s/%s" % (BLOB, rel), body)

open(os.path.join(OUT, "index.tsv"), "w", encoding="utf-8").write("\n".join(rows) + "\n")
print("==> Miasm: %d API modules + guides/cheatsheets, %d index rows" % (api, len(rows)))
PY
rm -rf "$SRC"
echo "index rows: $(wc -l < "$OUT/index.tsv")"
